# Generated by Django 4.2.1 on 2023-10-18 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='موظف بدون أسم', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='مجموعة بدون عنوان', max_length=255)),
                ('required_hours', models.PositiveIntegerField(default=0)),
                ('required_minutes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='سنة بدون عنوان', max_length=10)),
                ('more_hours', models.PositiveIntegerField(default=0)),
                ('more_minutes', models.PositiveIntegerField(default=0)),
                ('less_hours', models.PositiveIntegerField(default=0)),
                ('less_minutes', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='years', to='main.employee')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='شهر في السنة', max_length=50)),
                ('more_hours', models.PositiveIntegerField(default=0)),
                ('more_minutes', models.PositiveIntegerField(default=0)),
                ('less_hours', models.PositiveIntegerField(default=0)),
                ('less_minutes', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='months', to='main.employee')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='main.year')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='main.group'),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='يوم في الشهر', max_length=50)),
                ('date_month', models.CharField(default=0, max_length=50)),
                ('date_day', models.CharField(default=0, max_length=50)),
                ('required_hours', models.PositiveIntegerField()),
                ('required_minutes', models.PositiveIntegerField()),
                ('attend_hour', models.PositiveIntegerField()),
                ('attend_minute', models.PositiveIntegerField()),
                ('leave_hour', models.PositiveIntegerField()),
                ('leave_minute', models.PositiveIntegerField()),
                ('more_hours', models.PositiveIntegerField(default=0)),
                ('more_minutes', models.PositiveIntegerField(default=0)),
                ('less_hours', models.PositiveIntegerField(default=0)),
                ('less_minutes', models.PositiveIntegerField(default=0)),
                ('total_hours', models.IntegerField(default=0)),
                ('total_minutes', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='main.employee')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='main.month')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='main.year')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
