# Generated by Django 4.2.5 on 2023-10-08 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('more_hours', models.PositiveIntegerField(default=0)),
                ('more_minutes', models.PositiveIntegerField(default=0)),
                ('less_hours', models.PositiveIntegerField(default=0)),
                ('less_minutes', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('more_hours', models.PositiveIntegerField(default=0)),
                ('more_minutes', models.PositiveIntegerField(default=0)),
                ('less_hours', models.PositiveIntegerField(default=0)),
                ('less_minutes', models.PositiveIntegerField(default=0)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.year')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('main_img', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='main.image')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_hours', models.PositiveIntegerField()),
                ('required_minutes', models.PositiveIntegerField()),
                ('attend_hour', models.PositiveIntegerField()),
                ('attend_minute', models.PositiveIntegerField()),
                ('leave_hour', models.PositiveIntegerField()),
                ('leave_minute', models.PositiveIntegerField()),
                ('more_hours', models.PositiveIntegerField(default=0)),
                ('more_minutes', models.PositiveIntegerField(default=0)),
                ('less_hours', models.PositiveIntegerField(default=0)),
                ('less_minutes', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.month')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.year')),
            ],
        ),
    ]
