# Generated by Django 4.2.5 on 2023-10-08 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_day_employee_alter_day_month_alter_day_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='main.year'),
        ),
        migrations.AlterField(
            model_name='year',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='main.group'),
        ),
    ]
