# Generated by Django 4.2.5 on 2023-10-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_month_year_alter_year_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='total_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='total_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
